// Export the whole Brücke trail as a readable markdown guide.
// Run with: bun scripts/export-trail.ts   (writes TRAIL.md to the repo root)
//
// Shows the human stuff — titles, hooks, teasers, key sentences, takeaways,
// table words — in trail reading order (core → sprigs → next core), with star
// gates between stretches and branch paths under their attach topics.
// Skips the machinery: exercises, word-id arrays, store internals.
import fs from "fs";
import path from "path";
import { TOPICS, TRAIL_GATES, TRAIL_BRANCHES, TOTAL_TOPICS } from "../src/data/curriculum";
import { LESSONS } from "../src/data/lessons";
import { compendium } from "../src/data/compendium";

const SHIFT_BADGES: Record<string, string> = {
  th_to_d: "TH → D",
  d_to_t: "D → T",
  p_to_pf_f: "P → PF / F",
  t_to_s_ss_z: "T → S / SS / Z",
  k_to_ch: "K → CH",
  v_to_b: "V / F → B",
  y_gh_to_g_ch: "Y → G & GH → CH",
  latin_ieren: "-ieren",
  strong_verbs_ablaut: "Ablaut",
};

const out: string[] = [];
const line = (s = "") => out.push(s);

const lessonById = new Map(LESSONS.map((l) => [l.id, l]));

function lessonSection(id: number, kind: "core" | "sprig" | "branch"): void {
  const lesson = lessonById.get(id);
  if (!lesson) {
    line(`### ${id} · *(hollow shell)*`);
    line();
    return;
  }
  const badge = lesson.shift_categories
    .map((c) => SHIFT_BADGES[c])
    .filter(Boolean)
    .join(" · ");
  const icon = kind === "core" ? "🟢" : kind === "branch" ? "🌿" : "🔸";
  line(`### ${icon} ${lesson.id} · ${lesson.title}`);
  line();
  line(`*${lesson.subtitle}*`);
  line();
  if (badge) line(`**Shifts:** \`${badge}\``);
  if (badge) line();
  const hookExcerpt = (() => {
    const text = lesson.hook.content.split(". ").slice(0, 2).join(". ").replace(/\.$/, "") + ".";
    return text.length > 200 ? text.slice(0, 197).replace(/\s+\S*$/, "") + "…" : text;
  })();
  line(`**${lesson.hook.title}** — ${hookExcerpt}`);
  line();
  line(`> 🔭 **Next:** ${lesson.summary.curiosity_teaser.replace(/^Next( up)?: */i, "")}`);
  line();
  line(`- 🗝️ ${lesson.summary.use_example.german} — *${lesson.summary.use_example.english}*`);
  line(`- 🧭 ${lesson.summary.takeaway}`);
  line();
  const words = lesson.table_word_ids
    .map((wid) => compendium.words[wid])
    .filter(Boolean)
    .map((w) => `${w.gender ? `${w.gender} ` : ""}${w.target_word} — *${w.english_cognate}*`);
  if (words.length) line(`**Table:** ${words.join(" · ")}`);
  line();
}

// ---------------------------------------------------------------------------
line("# 🥾 The Brücke Trail — Complete Trail Guide");
line();
line(
  `> Generated by \`bun scripts/export-trail.ts\` — **${LESSONS.length} lessons** across **${TOTAL_TOPICS} topics**,`,
);
line("> told in trail order: each lesson's teaser points at the next stop on the map.");
line("> *You already understand more German than you think.*");
line();
line("---");
line();

for (const topic of TOPICS) {
  const gate = TRAIL_GATES.find((g) => g.afterTopic === topic.id);
  line(`## 📍 Topic ${topic.id} — ${topic.title}`);
  line();
  line(`> ${topic.blurb}`);
  line();

  lessonSection(topic.core.id, "core");
  for (const sprig of topic.sprigs) lessonSection(sprig.id, "sprig");

  for (const branch of TRAIL_BRANCHES.filter((b) => b.attach === topic.id)) {
    line(`#### 🌿 Side path — ${branch.title}`);
    line();
    line(`> ${branch.blurb}`);
    line();
    for (const l of branch.lessons) lessonSection(l.id, "branch");
  }

  if (gate) {
    line(`## 🚪 ${gate.title}`);
    line();
    line(`> **${gate.requiredStars}★ required** (earned across topics up to ${topic.id}). ${gate.why}`);
    line();
    line("---");
    line();
  } else if (topic.id !== TOTAL_TOPICS) {
    line("---");
    line();
  }
}

line("*End of the trail — willkommen auf der anderen Seite der Brücke.* 🌉");
line();

const outPath = path.resolve(__dirname, "../TRAIL.md");
fs.writeFileSync(outPath, out.join("\n"), "utf-8");
console.log(
  `[Brücke Trail Export] ${LESSONS.length} lessons, ${TOPICS.length} topics, ${TRAIL_GATES.length} gates → ${outPath}`,
);
